version: '3'
services:
  zookeeper:
    image: indigodatacloud/zookeeper
    network_mode: host
    environment:
      - MYID=1
      - SERVERS=localhost


  mesos_master:
    image: indigodatacloud/mesos-master
    network_mode: host
    environment:
      - MESOS_HOSTNAME=${DOCKER_IP}
      - MESOS_IP=${DOCKER_IP}
      - MESOS_CLUSTER=Mesos
      - MESOS_ZK=zk://127.0.0.1:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_OFFER_TIMEOUT=30secs
    depends_on:
      - zookeeper


  slave-one:
    image: indigodatacloud/mesos-slave
    network_mode: host
    pid: host
    privileged: true
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: ${DOCKER_IP}
      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/mesos:/tmp/mesos
    depends_on:
      - zookeeper
      - mesos_master


  chronos:
    image: indigodatacloud/chronos:indigo_2
    network_mode: host
    environment:
      - LIBPROCESS_IP=${DOCKER_IP}
      - CHRONOS_HOSTNAME=${DOCKER_IP}
      - CHRONOS_HTTP_PORT=4400
      - CHRONOS_MASTER=zk://127.0.0.1:2181/mesos
      - CHRONOS_ZK_HOSTS=zk://127.0.0.1:2181
      - CHRONOS_ZK_PATH=/chronos/state
      - CHRONOS_MESOS_FRAMEWORK_NAME=chronos
      - CHRONOS_HTTP_CREDENTIALS=admin:s3cret

